console:
  email: admin@rafay.co
  mfa_secret: 
  partner_id: "4qkolkn"
  password: 
  test_org:
    name: "onprem-qa"
    email: "onprem@rafay.co"
    password: ""
    first_name: "onprem"
    last_name: "qa"
controller:
  controller_size: S
  ha: true
  ip: 
  os_type: ubuntu24
  provision: true
  secondary_ips: []
  ssh_key: /Users/vijay/Documents/rafay-pytest-framework/keys/oci.key
  user: ubuntu
dns:
  aws_profile: vijay-aws
  base_domain: dev.rafay-edge.net
  hosted_zone_id: Z1OM749F0P8E4R
  ttl: 60
kubectl:
  default_namespace: rafay-system
  kubeconfig_path: ~/.kube/config
oci:
  availability_domain: PaOl:PHX-AD-1
  boot_timeout: 300
  boot_volume_gb: 1100
  compartment_id: ocid1.compartment.oc1..aaaaaaaadbipnkdi7rrn6ksl3ar64cn27uu2wd63ek7w7nx7e3fnk5n5omiq
  config_file: ~/.oci/config
  data_volume_gb: 1024
  display_name: shc-{build_no}
  image_id: ocid1.image.oc1.phx.aaaaaaaawcv7nuujttlzc3rdgw4svfbnbqlyh7cp5tje27wcseaipgdqm3eq
  nsg_id: ocid1.networksecuritygroup.oc1.phx.aaaaaaaaadw43qbzlrucw7ulmspk5obfhugfnrckxoob4nlsinr3cuupne5q
  profile: DEFAULT
  shape: VM.Standard.E5.Flex
  ssh_public_key: /Users/vijay/Documents/rafay-pytest-framework/keys/oci.key.pub
  subnet_id: ocid1.subnet.oc1.phx.aaaaaaaaxc7ait6l2jrhdvmahoeefwyliua27uic4l7iha4ynykmabz5sjkq
  tags:
    env: dev
    owner: vijay@rafay.co
    project: rafay-airgap
  vcn_id: ocid1.vcn.oc1.phx.amaaaaaaymbj47qaaozxzu7c2msuz3qxnji4evyzzfwrrqx7jo2zxabkl2bq
package:
  install_dir: /opt/rafay
  name: rafay-airgapped-controller-v3.1-40.tar.gz
  url: ''
reporting:
  output_dir: reports
